# MangoWC config loader

# Export the compositor session environment to systemd user services
exec-once=dbus-update-activation-environment --systemd --all

# Actually bring up the target your service is tied to
exec-once=systemctl --user start graphical-session.target

# Start Noctalia (direct, no systemd)
exec-once=/usr/bin/qs -c noctalia-shell


# This file just sources the real config from conf.d/
# (00-env.conf also runs autostart.sh via exec-once)
source=./conf.d/00-env.conf
source=./conf.d/10-effects.conf
source=./conf.d/20-animations.conf
source=./conf.d/30-layout.conf
source=./conf.d/40-input.conf
source=./conf.d/45-appearance.conf
source=./conf.d/50-monitors.conf
source=./conf.d/60-tagrules.conf

# Keybindings
source=./conf.d/binds/00-system.conf
source=./conf.d/binds/10-launchers-apps.conf
source=./conf.d/binds/20-windows.conf
source=./conf.d/binds/30-navigation.conf
source=./conf.d/binds/40-tags.conf
source=./conf.d/binds/50-pointer.conf
source=./conf.d/binds/60-display-layouts.conf

# Always safe to keep present (can be empty).
source=./conf.d/99-local.conf

# This sources the noctalia theme


# Theme (Noctalia)
source=./noctalia.conf
