# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0x99cbffff
maximizescreencolor = 0xb9c8daff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd4bee6ff
globalcolor = 0x004a78ff
overlaycolor = 0x3a4857ff
