# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0xb5c4ffff
maximizescreencolor = 0xc1c5ddff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe3badbff
globalcolor = 0x274190ff
overlaycolor = 0x414659ff
