# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131314ff
bordercolor = 0x8f9195ff
focuscolor = 0xc1c7d1ff
maximizescreencolor = 0xc6c6caff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd0c3ceff
globalcolor = 0x41474fff
overlaycolor = 0x45474aff
