# Split from original config.conf (2026-01-13 17:55:57Z UTC)
# Original: config.conf

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=1
xkb_rules_layout=gb
#localectl set-x11-keymap gb


# Trackpad
# need relogin to make it apply
disable_trackpad=1
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
