# Monitor layout
#
# Current machine:
#   DP-3      left monitor
#   HDMI-A-1 right / primary gaming monitor
#
# HDMI-A-1 is positioned to the right of DP-3.

monitorrule=name:DP-3,width:1920,height:1080,refresh:60,x:0,y:0,scale:1,vrr:0,rr:0

monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:143.981003,x:1920,y:0,scale:1,vrr:0,rr:0
