# Split from original config.conf (2026-01-13 17:55:57Z UTC)
# Original: config.conf

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
# Keep tags 1–5 persistent on DP-2 (left)
tagrule=id:1,monitor_name:DP-2,no_hide:1
tagrule=id:2,monitor_name:DP-2,no_hide:1
tagrule=id:3,monitor_name:DP-2,no_hide:1
tagrule=id:4,monitor_name:DP-2,no_hide:1
tagrule=id:5,monitor_name:DP-2,no_hide:1

# Keep tags 6–9 persistent on HDMI-A-1 (right)
tagrule=id:6,monitor_name:HDMI-A-1,no_hide:1
tagrule=id:7,monitor_name:HDMI-A-1,no_hide:1
tagrule=id:8,monitor_name:HDMI-A-1,no_hide:1
tagrule=id:9,monitor_name:HDMI-A-1,no_hide:1
tagrule=id:0,monitor_name:HDMI-A-1,no_hide:1




# =============================
