# Split from original config.conf (2026-01-13 17:55:57Z UTC)
# Original: config.conf

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
# Keep tags 1–5 persistent on DP-2 (left)
tagrule=id:1,no_hide:1,layout_name:scroller
tagrule=id:2,no_hide:1,layout_name:scroller
tagrule=id:3,no_hide:1,layout_name:scroller
tagrule=id:4,no_hide:1,layout_name:scroller
tagrule=id:5,no_hide:1,layout_name:scroller

# Keep tags 6–9 persistent on HDMI-A-1 (right)
tagrule=id:6,no_hide:1,layout_name:scroller
tagrule=id:7,no_hide:1,layout_name:scroller
tagrule=id:8,no_hide:1,layout_name:scroller
tagrule=id:9,no_hide:1,layout_name:scroller

