# =============================
# Applications 
# =============================
bind=SUPER,space,spawn_shell,mango-run launcher
bind=SUPER,Return,spawn_shell,mango-run terminal
bind=SUPER+ALT,Return,spawn_shell,mango-run alternate_terminal
bind=SUPER+SHIFT,Return,spawn_shell,mango-run terminal_filemanager
bind=SUPER+ALT,b,spawn_shell,mango-run browser
bind=SUPER+ALT,f,spawn_shell,mango-run filemanager
bind=SUPER+ALT,d,spawn_shell,mango-run coding
bind=SUPER+ALT,m,spawn_shell,mango-run musicplayer
bind=SUPER+ALT,n,spawn_shell,mango-run video
bind=SUPER+ALT,y,spawn_shell,mango-run streaming
bind=SUPER+ALT,s,spawn_shell,mango-run samcoupe
bind=SUPER+ALT,c,spawn_shell,mango-run speccynext
bind=SUPER+SHIFT,s,spawn_shell,mango-run gaming
bind=SUPER+ALT,g,spawn_shell,mango-run graphics
bind=SUPER+ALT,p,spawn_shell,mango-run writing
bind=SUPER+ALT,x,spawn_shell,mango-run spreadsheet
bind=SUPER+CTRL,f,spawn_shell,pick-file

