# =============================
# User Interface
# =============================


# Capture Screens
bind=SUPER,Print,spawn_shell,mango-run capture-all-screens
bind=SUPER+SHIFT,Print,spawn_shell,mango-run capture-part-screen
bind=SUPER+CTRL,Print,spawn_shell,mango-run capture-current-screen
bind=SUPER+ALT,Print,spawn_shell,mango-run capture-separate-screens

#bind=SUPER+CTRL,e,spawn_shell,sh -c 'command -v $HOME/.config/mango/scripts/toggle-all-floating && notify-send "Mango" "bind fired"'


# Nocatalia Shell Settings
# =========================

# Toggle Noctalia dock (same key shows/hides)
bind=SUPER+CTRL,d,spawn,qs -c noctalia-shell ipc call dock toggle

# Clipper (Noctalia clipboard panel)
bind=SUPER+CTRL,v,spawn,qs -c noctalia-shell ipc call launcher clipboard

# Nocatalia Settings
bind=SUPER+CTRL,s,spawn,qs -c noctalia-shell ipc call settings toggle

# Wallpaper Selector
bind=SUPER+CTRL,w,spawn,qs -c noctalia-shell ipc call wallpaper toggle

# Toggle Bar
bind=SUPER+CTRL,b,spawn,qs -c noctalia-shell ipc call bar toggle

# Dark Mode
bind=SUPER+CTRL,m,spawn,qs -c noctalia-shell ipc call darkMode toggle

# Calendar
bind=SUPER+CTRL,t,spawn,qs -c noctalia-shell ipc call calendar toggle

# Lock and Suspend
bind=SUPER+CTRL,l,spawn,qs -c noctalia-shell ipc call sessionMenu lockAndSuspend

# Notifications History
bind=SUPER+CTRL,n,spawn,qs -c noctalia-shell ipc call notifications toggleHistory

# Control Centre
bind=SUPER+CTRL,c,spawn,qs -c noctalia-shell ipc call controlCenter toggle
