# =============================
# Tags (1..9)
# =============================
#
# View tags
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

# View all tags
bind=SUPER,0,view,0

# Keypad view tags
bind=SUPER,KP_End,view,1
bind=SUPER,KP_Down,view,2
bind=SUPER,KP_Next,view,3
bind=SUPER,KP_Left,view,4
bind=SUPER,KP_Begin,view,5
bind=SUPER,KP_Right,view,6
bind=SUPER,KP_Home,view,7
bind=SUPER,KP_Up,view,8
bind=SUPER,KP_Prior,view,9
bind=SUPER,KP_Insert,view,0

# Move focused window to tag
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

# Keypad move-to-tag (SHIFT version)
bind=SUPER+SHIFT,KP_End,tag,1
bind=SUPER+SHIFT,KP_Down,tag,2
bind=SUPER+SHIFT,KP_Next,tag,3
bind=SUPER+SHIFT,KP_Left,tag,4
bind=SUPER+SHIFT,KP_Begin,tag,5
bind=SUPER+SHIFT,KP_Right,tag,6
bind=SUPER+SHIFT,KP_Home,tag,7
bind=SUPER+SHIFT,KP_Up,tag,8
bind=SUPER+SHIFT,KP_Prior,tag,9

# Next/previous tag
bind=SUPER,Tab,viewtoright_have_client
bind=SUPER+SHIFT,Tab,viewtoleft_have_client

# Mouse wheel tag switching
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client


# =============================
