


# Switch focus between monitors (cycle)
# bind=SUPER+ALT,Tab,focusmon,right
# bind=SUPER+ALT+SHIFT,Tab,focusmon,left

# Switch focus between monitors (by direction)
bind=SUPER+ALT,Left,focusmon,left
bind=SUPER+ALT,Right,focusmon,right
bind=SUPER+ALT,Up,focusmon,up
bind=SUPER+ALT,Down,focusmon,down

# Switch to named monitor
bind=SUPER+ALT,1,focusmon,DP-3
bind=SUPER+ALT,2,focusmon,HDMI-A-1


# Move focused window to another monitor (by direction)
# keeptag: 0/1 controls whether Mango keeps the window's tag when moving it across monitors
bind=SUPER+ALT+SHIFT,Left,tagmon,l,0
bind=SUPER+ALT+SHIFT,Right,tagmon,r,0
bind=SUPER+ALT+SHIFT,Up,tagmon,u,0
bind=SUPER+ALT+SHIFT,Down,tagmon,d,0

