# Split from original config.conf (2026-01-13 17:55:57Z UTC)
# Original: config.conf


# =============================
# Display / Layout switching (from display.conf)
# =============================
bind=SUPER,F1,setlayout,scroller
bind=SUPER,F2,setlayout,master
bind=SUPER,F3,setlayout,vertical_spiral
# Other horizontal layouts
bind=SUPER,F4,setlayout,monocle
bind=SUPER,F5,setlayout,grid
bind=SUPER,F6,setlayout,deck
bind=SUPER,F7,setlayout,center_tile
bind=SUPER,F8,setlayout,right_tile

# Other vertical layouts
bind=SUPER,F9,setlayout,vertical_tile
bind=SUPER,F10,setlayout,vertical_scroller
bind=SUPER,F11,setlayout,vertical_grid
bind=SUPER,F12,setlayout,vertical_deck

# Special
bind=SUPER+CTRL,F12,setlayout,tgmix

# Wallpaper Selector
bind=SUPER, W, spawn_shell, qs -c noctalia-shell ipc call wallpaper toggle
#bind=SUPER, W, spawn_shell, qs -c noctalia-shell ipc call wallpaper next && $HOME/.local/bin/noctalia-sync-sddm-wallpaper
# "w" is commonly code:25 (verify with `wev`)
#bind=SUPER+SHIFT,code:25,spawn_shell,qs -c noctalia-shell ipc call wallpaper toggle
#bind=SUPER+SHIFT,w,spawn_shell,qs -c noctalia-shell ipc call toast send '{"title":"Mango bind fired"}'

