# =============================
# Layout cycling
# =============================

circle_layout=tile,scroller,monocle,grid,deck,center_tile,right_tile,vertical_tile,vertical_scroller,vertical_grid,vertical_deck,dwindle,fair,vertical_fair

bind=SUPER,F1,switch_layout

# =============================
# Frequently used layouts
# =============================

bind=SUPER,F2,setlayout,dwindle
bind=SUPER,F3,setlayout,scroller
bind=SUPER,F4,setlayout,center_tile
bind=SUPER,F5,setlayout,tile
bind=SUPER,F6,setlayout,monocle
bind=SUPER,F7,setlayout,grid
bind=SUPER,F8,setlayout,deck
bind=SUPER,F9,setlayout,right_tile
bind=SUPER,F10,setlayout,fair

# =============================
# Vertical layouts
# =============================

bind=SUPER+CTRL,F1,setlayout,vertical_tile
bind=SUPER+CTRL,F2,setlayout,vertical_scroller
bind=SUPER+CTRL,F3,setlayout,vertical_grid
bind=SUPER+CTRL,F4,setlayout,vertical_deck
bind=SUPER+CTRL,F5,setlayout,vertical_fair
